sudo: false
cache: bundler
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
matrix:
  include:
    - rvm: 2.5.1
      env: JEKYLL_VERSION=3.7.4
env:
  matrix:
    - JEKYLL_VERSION=3.8.4
branches:
  only:
    - master
before_install:
- gem update --system
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} %{message} %{build_url}'
  email:
    on_success: never
    on_failure: change
